require('./ts-loader.cjs');
const assert=require('assert'),Module=require('module');
const original=Module._load,storage=new Map();
Module._load=function(id,...args){if(id==='cc')return {_decorator:{ccclass:()=>T=>T},Component:class{},sys:{localStorage:{setItem:(k,v)=>storage.set(k,v)}}};return original.call(this,id,...args);};
const {Main}=require('../assets/scripts/Main.ts');Module._load=original;
const m=new Main();let labels=[];
m.root={removeAllChildren(){labels=[];}};
m.make=()=>({active:false,removeAllChildren(){}});
m.panel=()=>{};m.artwork=()=>{};
m.text=(parent,text)=>{labels.push(text);return {string:text};};
m.button=(parent,label,x,y,w,run,primary,h=62)=>{m.buttons.push({label,x,y,w,h,run});};
m.showHome();assert(labels.includes('第1关'));assert(labels.includes('已通关0关'));
let opened=-1;m.openLevel=i=>opened=i;
m.point=e=>e;
const start=m.buttons.find(b=>b.label==='');
const event={x:start.x,y:start.y,getID:()=>1};m.startTouch(event);m.endTouch(event);
assert.equal(opened,0,'home start works before any session exists');
m.session={level:{id:'test',arrows:Array(74)},removed:new Set(),hearts:3,status:'playing',snapshot:()=>({})};
m.hearts={};m.progress={};m.updateHUD();assert.equal(m.progress.string,'0%');
m.session.removed=new Set(Array.from({length:37},(_,i)=>i));m.updateHUD();assert.equal(m.progress.string,'50%');
m.session.removed=new Set(Array.from({length:74},(_,i)=>i));m.updateHUD();assert.equal(m.progress.string,'100%');
m.saved={completed:10};m.index=10;m.session.status='won';m.save();m.showHome();
assert(labels.includes('第12关'));assert(labels.includes('已通关11关'));
m.index=20;m.save();assert.equal(m.nextLevel(),11,'demo jumping must not mark unplayed levels complete');
m.saved={completed:10};m.session.status='playing';m.showHome();assert(labels.includes('第11关'));
console.log('PASS UI flow: first-launch home touch, next-level progress, 0/50/100 percent, no false completions from demo jumps.');
